### PR TITLE
- Includes fixes for the following issues:

### PR DESCRIPTION
**Pull request by rbargerhuff**
* #18: Improves Array Short Syntax handling. See for more info: https://github.com/backdrop-contrib/coder_upgrade/issues/18
  * #39: Nullable Types not being handled correctly when associated with the array type. See for more info:  https://github.com/backdrop-contrib/coder_upgrade/issues/39
  * #40: Includes the handling of namespaces, including use statements. See for more info: https://github.com/backdrop-contrib/coder_upgrade/issues/40

### CODE REVIEW

**Comment by rbargerhuff** [comment]
Contributions made for issue #40 have been cherry picked from the latest version of the 7.x-2.x branch of Grammar Parser.
https://git.drupalcode.org/project/grammar_parser

**Comment by herbdool** [comment]
Would you have an example contrib module which we could use to test your PR against? Or some sample code?

**Comment by rbargerhuff** [comment]
I created a repo of a basic test module we are using to help facilitate testing of the conversion process.

https://github.com/rbargerhuff/backdrop_conversion_test

We also managed to convert the Views PHP module successfully after the changes we made were applied.
https://www.drupal.org/project/views_php

**Comment by bugfolder** [comment]
Tested and works as advertised! Thanks for putting this together. I'll also adopt your test code into a testing module that will be forthcoming shortly.

**Comment by rbargerhuff** [comment]
Follow up: Has there been any movement on this? Thanks.

**Pull request merged**
